version: '3'

services:
  db:
    image: postgres:14

    env_file:
      - .env

    ports:
      - 5432:5432
      - 8000:8000

    volumes:
      - postgres-data:/var/lib/postgresql/data 
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db

    network_mode: service:db

volumes:
  postgres-data: