version: '3'

services:
  playwright:
    image: mcr.microsoft.com/playwright/python:v1.30.0-focal
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "pip install -r requirements_test.txt && pytest -v"
    depends_on:
      - app
    network_mode: service:db

  locust_main:
    image: locustio/locust
    ports:
      - 8089:8089
    volumes:
      - .:/locust
    working_dir: /app
    command: bash -c "pip install -r requirements_test.txt && locust -f locustfile.py --host=http://master:8089"

  locust_worker:
    image: locustio/locust
    volumes:
      - .:/locust
    command: bash -c "pip install -r requirements_test.txt && locust -f locustfile.py --host=http://master:8089 --worker --master-host=master"
    depends_on:
      - locust_main

  db:
    image: postgres:14

    env_file:
      - .env

    ports:
      - 5432:5432
      - 8000:8000
      - 8089:8089

    volumes:
      - postgres-data:/var/lib/postgresql/data 
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db

    network_mode: service:db

volumes:
  postgres-data: