name: Test
on: [push, pull_request]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v4
          with:
                python-version: 3.11
                cache: 'pip'
        - name: Check Format
          run: |
                pip install -r ruff black
                ruff .
                black . --check --verbose