name: Test
on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
jobs:
    checks-format:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v4
          with:
                python-version: 3.11
                cache: 'pip'
        - name: Check Format
          run: |
                pip install ruff black
                ruff .
                black . --check --verbose
